{
 "title": "Private Cloud Billing Dashboard",
 "description": "Billing Metrics For Cluster is slightly different that what billing reporter uses.  This query is what billing reporter uses assuming hosted",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(pulsar_version_info,kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Usage for customer $ns",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "ns",
   "targets": [
    {}
   ]
  },
  {
   "title": "Compute Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "((max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"cpu\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(broker|proxy)\",job=\"kube-state-metrics\"}) by (namespace) [1h:]) * 1000) / 2000) > (max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(broker|proxy)\",job=\"kube-state-metrics\"}) by (namespace) [1h:]) / 8589934592) or (max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(broker|proxy)\",job=\"kube-state-metrics\"}) by (namespace) [1h:]) / 8589934592)",
     "legendFormat": "{{label_cloud_streamnative_io_cluster}}"
    }
   ]
  },
  {
   "title": "Storage Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "((max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"cpu\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(bookie|zookeeper)\",job=\"kube-state-metrics\"}) by (namespace) [1h:]) * 1000) / 2000) > (max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(bookie|zookeeper)\",job=\"kube-state-metrics\"}) by (namespace) [1h:]) / 8589934592) or (max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(bookie|zookeeper)\",job=\"kube-state-metrics\"}) by (namespace) [1h:]) / 8589934592)",
     "legendFormat": "{{label_cloud_streamnative_io_cluster}}"
    }
   ]
  },
  {
   "title": "Compute Units Sum By Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "((sum_over_time(max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"cpu\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(broker|proxy)\",job=\"kube-state-metrics\"}) by (namespace) [1h:])[23h:1h]) * 1000) / 2000) > (sum_over_time(max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(broker|proxy)\",job=\"kube-state-metrics\"}) by (namespace) [1h:])[23h:1h]) / 8589934592) or (sum_over_time(max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(broker|proxy)\",job=\"kube-state-metrics\"}) by (namespace) [1h:])[23h:1h]) / 8589934592)",
     "legendFormat": "{{label_cloud_streamnative_io_cluster}}"
    }
   ]
  },
  {
   "title": "Storage Units By Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "((sum_over_time(max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"cpu\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(bookie|zookeeper)\",job=\"kube-state-metrics\"}) by (namespace) [1h:])[23h:1h]) * 1000) / 2000) > (sum_over_time(max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(bookie|zookeeper)\",job=\"kube-state-metrics\"}) by (namespace) [1h:])[23h:1h]) / 8589934592) or (sum_over_time(max_over_time(sum(kube_pod_container_resource_requests{namespace=~\"$ns\", resource=\"memory\",job=\"kube-state-metrics\"} * on (pod) group_left(namespace) kube_pod_labels{namespace=~\"$ns\",label_cloud_streamnative_io_component =~\"(bookie|zookeeper)\",job=\"kube-state-metrics\"}) by (namespace) [1h:])[23h:1h]) / 8589934592)",
     "legendFormat": "{{label_cloud_streamnative_io_cluster}}"
    }
   ]
  }
 ]
}