{
 "title": "Broker Load Balancer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cloud_streamnative_io_cluster=~\".+\"}"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "pulsar_lb_memory_usage{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\".+\"}"
    }
   },
   {
    "name": "cache",
    "label": "Cache Name",
    "query": {
     "query": "caffeine_cache_hit_total{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LoadBalance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pulsar_lb_bandwidth_out_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_out_usage{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bandwidth_in_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bandwidth_in_usage{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_memory_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_memory_usage{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_directMemory_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_directMemory_usage{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_cpu_usage{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_bundles_split_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_bundle_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_unload_bundle_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_broker_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_unload_broker_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_topics_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_topics_count{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "caffeine_cache_estimated_size{cache=~\"owned-bundles\"}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(caffeine_cache_estimated_size{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",cache=~\"owned-bundles\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "LoadBalance Extension -- Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pulsar_lb_resource_usage -- max_ema",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 *  pulsar_lb_resource_usage{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\", feature=\"max_ema\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_resource_usage_stats -- avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * pulsar_lb_resource_usage_stats{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\", feature=\"max_ema\", stat=\"avg\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_resource_usage_stats -- std",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_resource_usage_stats{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\", feature=\"max_ema\", stat=\"std\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_assign_broker_breakdown_total -- success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_assign_broker_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Success\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_assign_broker_breakdown_total -- skip",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_assign_broker_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Skip\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_assign_broker_breakdown_total -- failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pulsar_lb_assign_broker_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_broker_breakdown_total -- success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_lb_unload_broker_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Success\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_broker_breakdown_total -- skip",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_lb_unload_broker_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Skip\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_unload_broker_breakdown_total -- failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_lb_unload_broker_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_breakdown_total -- success_by_reason",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_lb_bundles_split_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Success\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_breakdown_total -- skip_by_reason",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_lb_bundles_split_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Skip\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_breakdown_total -- failure_by_reason",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_lb_bundles_split_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_breakdown_total -- success_by_broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(pulsar_lb_bundles_split_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Success\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_breakdown_total -- skip_by_broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "sum(pulsar_lb_bundles_split_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Skip\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_lb_bundles_split_breakdown_total -- failure_by_broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "sum(pulsar_lb_bundles_split_breakdown_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "LoadBalance Extension -- ServiceUnitStateChannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_owner_lookup_total -- total_increase_by_broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Total\"} [1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_owner_lookup_total -- failure_increase_by_broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_owner_lookup_total -- total_increase_by_state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Total\"} [1m])) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_owner_lookup_total -- failure_increase_by_state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_owner_lookup_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}[1m])) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_event_publish_ops_total -- total_increase_by_broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Total\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_event_publish_ops_total -- failure_increase_by_broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_event_publish_ops_total -- total_increase_by_event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Total\"} [1m])) by (event)",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_event_publish_ops_total -- failure_increase_by_event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_event_publish_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"} [1m])) by (event)",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_subscribe_ops_total -- total_increase_by_broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Total\"} [1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_subscribe_ops_total -- failure_increase_by_broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}[1m] )) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_subscribe_ops_total -- total_increase_by_event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Total\"}[1m] )) by (event)",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_subscribe_ops_total -- failure_increase_by_event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 79 },
   "targets": [
    {
     "expr": "sum(increase(pulsar_sunit_state_chn_subscribe_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"}[1m] )) by (event)",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_inactive_broker_cleanup_ops_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_sunit_state_chn_inactive_broker_cleanup_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"}) by (result)",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_su_tombstone_cleanup_ops_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_sunit_state_chn_su_tombstone_cleanup_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"} ) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_orphan_su_cleanup_ops_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_sunit_state_chn_orphan_su_cleanup_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"} ) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_cleanup_ops_failure_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_sunit_state_chn_cleanup_ops_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\",result=\"Failure\"} ) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pulsar_sunit_state_chn_owned_su_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(pulsar_sunit_state_chn_owned_su_total{cloud_streamnative_io_cluster=~\"$cluster\",pod=~\"$pod\"} ) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}