{
 "title": "Overview",
 "description": "Overview of Pulsar Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cloud_streamnative_io_cluster=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "PersistentVolume Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (kubelet_volume_stats_available_bytes / on (persistentvolumeclaim) kubelet_volume_stats_capacity_bytes))",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes - node_filesystem_avail_bytes)  / node_filesystem_size_bytes",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ( 1 - \n   ( sum(increase(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n    / \n   sum(increase(node_cpu_seconds_total{}[5m]))\n  )\n)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{}) / sum(node_memory_MemTotal_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "Pulsar Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeeper",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cloud_streamnative_io_component=\"zookeeper\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Bookies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cloud_streamnative_io_component=\"bookie\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cloud_streamnative_io_component=\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cloud_streamnative_io_component=\"proxy\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{cloud_streamnative_io_component=\"function\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Backlog (bytes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Backlog (msgs)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Zookeeper Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{cloud_streamnative_io_component=\"zookeeper\", cloud_streamnative_io_cluster=~\"$cluster\"} == 1) / count(up{cloud_streamnative_io_component=\"zookeeper\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bookies Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{cloud_streamnative_io_component=\"bookie\", cloud_streamnative_io_cluster=~\"$cluster\"} == 1) / count(up{cloud_streamnative_io_component=\"bookie\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Brokers Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{cloud_streamnative_io_component=\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"} == 1) / count(up{cloud_streamnative_io_component=\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Proxies Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{cloud_streamnative_io_component=\"proxy\", cloud_streamnative_io_cluster=~\"$cluster\"} == 1) / count(up{cloud_streamnative_io_component=\"proxy\", cloud_streamnative_io_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Functions Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{cloud_streamnative_io_component=\"function\"} == 1) / count(up{cloud_streamnative_io_component=\"function\"})"
    }
   ]
  },
  {
   "title": "Messaging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messaging Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Backlog (size)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Backlog (msgs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Message Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - In"
    },
    {
     "expr": "sum(pulsar_rate_out{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - Out"
    }
   ]
  },
  {
   "title": "Top 10 namespace storage size (bytes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum(pulsar_storage_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 10 namespace backlog (bytes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sum(pulsar_storage_backlog_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - In"
    },
    {
     "expr": "sum(pulsar_throughput_out{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }} - Out"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Top 10 topics storage size (bytes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_storage_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (topic))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Top 10 topics backlog (bytes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "topk(10, sum(pulsar_storage_backlog_size{cloud_streamnative_io_component=~\"broker\", cloud_streamnative_io_cluster=~\"$cluster\"}) by (topic))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - (sum(increase(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (pod)\n/ \nsum(increase(node_cpu_seconds_total[5m])) by (pod)))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 ",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}