{
 "title": "Proxy Metrics",
 "description": "Proxy Metrics",
 "tags": [ "proxy" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cloud_streamnative_io_cluster=~\".+\"}"
    }
   },
   {
    "name": "pod",
    "label": "Proxy",
    "query": "pulsar_proxy_active_connections{pod=~\".+\", cloud_streamnative_io_component=~\"proxy\",cloud_streamnative_io_cluster=~\"$cluster\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_proxy_active_connections{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "New connections (conn / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_new_connections_total{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rejected connections (conn / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_rejected_connections_total{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_binary_ops_total{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traffic - bytes per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_binary_ops_total{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP  reqs per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jetty_requests_total{cloud_streamnative_io_cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Topic lookups per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_lookup_requests{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GetPartitionsMetadata per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_partitions_metadata_requests{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GetNamespaceTopics per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_get_topics_of_namespace_requests{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lookups rejected per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_rejected_lookup_requests{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Partitions requests rejected per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_proxy_rejected_partitions_metadata_requests{cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GetNamespaceTopics requests rejected per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    pulsar_proxy_rejected_get_topics_of_namespace_requests{\n            cloud_streamnative_io_cluster=~\"$cluster\", cloud_streamnative_io_component=~\"proxy\", \n            pod=~\"$pod\"}[5m]\n    )\n  ) \nby (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}