{
 "title": "pulsar_detector",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cloud_streamnative_io_cluster=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "E2E Failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "E2E Failure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(pulsar_detector_e2e_latency_ms_count{cloud_streamnative_io_cluster=\"$cluster\",success=\"false\"} [5m] offset 5m)",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  { "title": "Publish latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Publish latency (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.5\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Publish latency (0.75)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.75\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Publish latency (0.9)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.9\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Publish latency (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.99\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Publish latency (0.999)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.999\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Publish latency (1)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "pulsar_detector_publish_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"1.0\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  { "title": "E2E latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "E2E latency (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "pulsar_detector_e2e_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.5\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "E2E latency (0.75)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "pulsar_detector_e2e_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.75\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "E2E latency (0.9)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "pulsar_detector_e2e_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.9\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "E2E latency (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "pulsar_detector_e2e_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.99\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "E2E latency (0.999)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "pulsar_detector_e2e_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"0.999\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "E2E latency (1)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "pulsar_detector_e2e_latency_ms{cloud_streamnative_io_cluster=\"$cluster\", quantile=\"1.0\", success=\"true\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  }
 ]
}