{
 "title": "Broker Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cluster=~\".+\"}"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "pulsar_rate_in{cluster=~\"$cluster\", kubernetes_pod_name=~\".+\"}"
   },
   {
    "name": "cache",
    "label": "Cache Name",
    "query": "caffeine_cache_hit_total{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Publish rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Dispatch rate (msg / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_out{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Dispatch throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_out{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Topics count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_topics_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Producers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)  ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Consumers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_consumers_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)  ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Publish Latency - 50pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99.9pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"0.999\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish Latency - Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"1.0\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Broker Cache - $cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "cache",
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caffeine_cache_estimated_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Evictions rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_eviction_total{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Hits / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_hit_total{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Misses / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_miss_total{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Loads / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_loads_total{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Avg load latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(caffeine_cache_load_duration_seconds_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[5m])/idelta(caffeine_cache_load_duration_seconds_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[5m])\n",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}