{
 "title": "Messaging Metrics",
 "description": "Messaging Related Metrics Per Namespace",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pulsar_topics_count{})" }
   ]
  },
  {
   "title": "Producers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pulsar_producers_count{})" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_subscriptions_count{})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pulsar_consumers_count{})" }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pulsar_storage_size{})" }
   ]
  },
  {
   "title": "Msg Backlog (bytes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{})"
    }
   ]
  },
  {
   "title": "Msg Backlog (msgs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pulsar_msg_backlog{})" }
   ]
  },
  { "title": "Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Local publish rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(pulsar_rate_in{})", "legendFormat": "{{cluster}} - {{namespace}}" }
   ]
  },
  {
   "title": "Local delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(pulsar_rate_out{})", "legendFormat": "{{cluster}} - {{namespace}}" }
   ]
  },
  {
   "title": "Local publish throughput (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sum(pulsar_throughput_in{})", "legendFormat": "{{cluster}} - {{namespace}}" }
   ]
  },
  {
   "title": "Local delivery throughput (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "sum(pulsar_throughput_out{})", "legendFormat": "{{cluster}} - {{namespace}}" }
   ]
  },
  {
   "title": "Topics - Producers - Subscriptions - Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(pulsar_topics_count{})", "legendFormat": "topics" },
    { "expr": "sum(pulsar_producers_count{})", "legendFormat": "producers" },
    {
     "expr": "sum(pulsar_subscriptions_count{})",
     "legendFormat": "subscriptions"
    },
    { "expr": "sum(pulsar_consumers_count{})", "legendFormat": "consumers" }
   ]
  },
  {
   "title": "Local backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(pulsar_msg_backlog{})", "legendFormat": "{{cluster}} - {{namespace}}" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Storage Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(pulsar_storage_size{})", "legendFormat": "$namespace" }
   ]
  },
  {
   "title": "Storage entry size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_entry_size_le_128{}) / 60.0",
     "legendFormat": "< 128 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_512{}) / 60.0",
     "legendFormat": "< 512 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_kb{}) / 60.0",
     "legendFormat": "< 1 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_2_kb{}) / 60.0",
     "legendFormat": "< 2 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_4_kb{}) / 60.0",
     "legendFormat": "< 4 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_16_kb{}) / 60.0",
     "legendFormat": "< 16 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_100_kb{}) / 60.0",
     "legendFormat": "< 100 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_mb{}) / 60.0",
     "legendFormat": "< 1 MB"
    },
    {
     "expr": "sum(pulsar_entry_size_overflow{}) / 60.0",
     "legendFormat": "> 1 MB"
    }
   ]
  }
 ]
}